Repository bedita/dev-tools, pull requests merged in 2022-09, with the labels that each got.

#24 Move HtmlMiddleware and skip authorization check for DebugKit
  src/Plugin.php
  tests/TestCase/PluginTest.php
Labels: bug

#25 Use reusable PHP workflows in CI [master, 2.x]
  .github/workflows/php.yml
Labels: enhancement

#26 Use reusable PHP workflows in CI [1.x]
  .github/workflows/php.yml
  src/Plugin.php
Labels: enhancement

#28 Release workflow in CI [1.x]
  .github/workflows/release.yml
Labels: enhancement, release:patch

#27 Release workflow in CI [master, 2.x]
  .github/workflows/release.yml
Labels: enhancement, release:patch
